name: Gated Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Do thing
      run: find . -name "compose.yml" -type f
      
    - name: Do other thing
      run: pwd 

    - name: Build Docker Compose
      run: docker compose -f ./client/compose.yml build
      
    - name: Verify services start
      run: |
        docker compose -f ./client/compose.yml up -d
        docker compose -f ./client/compose.yml down

