name: Build and Test Docker Image

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./client/Dockerfile
        push: false
        tags: onioncall-dev:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # Optional: Run tests inside the container
    - name: Test Docker image
      run: |
        docker run --rm onioncall-dev:test [test-command]
        # Example: docker run --rm myapp:test go test ./...
        # Or: docker run --rm myapp:test dotnet test
